import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import events from './routes/events.js';
import resources from './routes/resources.js';
import contact from './routes/contact.js';
const app=express();
app.use(helmet());
app.use(cors({origin:process.env.CLIENT_ORIGIN||'http://localhost:5173'}));
app.use(express.json({limit:'20kb'}));
app.get('/api/health',(_req,res)=>res.json({status:'ok'}));
app.use('/api/events',events);app.use('/api/resources',resources);app.use('/api/contact',contact);
app.use((req,res)=>res.status(404).json({error:'Route not found'}));
app.use((err,_req,res,_next)=>{console.error(err);res.status(500).json({error:'Internal server error'});});
const port=Number(process.env.PORT)||5000;
app.listen(port,()=>console.log(`IEEE SB VVITU API listening on ${port}`));
